Attempt to fix a killpit broken by a prior commit
 Error:  (00000014): cannot be moved to a None object's location.
stack:
	[ (00000014)].Actor.MoveTo() - "<native>" Line ?
	[ (0F32949F)]._Lull_InstakillPitScript.OnTriggerEnter() - "_Lull_InstakillPitScript.psc" Line 17